---
execute:
  echo: false
  message: false
  warning: false
---

```{r}
library(shiny)
library(bslib)
```

```{r}
layout_columns(
  card(
    p("Hola")
  ),
  card(
    p("Chao")
  )
)
```


¿Estás recién pensando en aprender R?

¿Nunca has programado pero quieres empezar ya?

¿Sabes un poco de R, pero necesitas reforzar?

¿Ya sabes programar en R y quieres mejorar?


## Por qué R
https://bastianolea.rbind.io/blog/r_introduccion/por_que_r/

```{r}
layout_columns(
  card(
    p("Gratuito")
  ),
  card(
    p("Amigable")
  ),
  card(
    p("Reproducible")
  )
)
```


## Primeros pasos

```{r}
card(
  p("Chao")
)
```


https://bastianolea.rbind.io/blog/r_introduccion/instalar_r/

https://bastianolea.rbind.io/blog/r_introduccion/r_basico/

https://bastianolea.rbind.io/blog/r_introduccion/r_intermedio/

## Reforzando lo básico

```{r}
card(
  layout_columns(
    col_widths = c(4, 8), 
    
    div(
    ),
    
    card(id = "interna",
         p("Chao")
    )
  )
)
```


https://bastianolea.rbind.io/blog/r_introduccion/proyectos/

## Empezar a trabajar con datos
https://bastianolea.rbind.io/blog/r_introduccion/dplyr_intro/

https://bastianolea.rbind.io/blog/r_introduccion/tutorial_dplyr_censo/

https://bastianolea.rbind.io/blog/r_introduccion/tutorial_dplyr_campamentos/


https://bastianolea.rbind.io/blog/left_join/


### Tidyverse

https://bastianolea.rbind.io/blog/stringr_texto/


## Estadísticas
https://bastianolea.rbind.io/blog/correlaciones/

----


## Nuevas posibilidades con R

```{r}
card(
  layout_columns(
    card(id = "interna",
         p("Chao")
    ),
    
    card(id = "interna",
         p("Chao")
    ),
    
    card(id = "interna",
         p("Chao")
    ),
    
    card(id = "interna",
         p("Chao")
    ),
  )
)
```


### Visualización de datos
https://bastianolea.rbind.io/blog/r_introduccion/tutorial_visualizacion_ggplot/

https://bastianolea.rbind.io/tags/visualización-de-datos/


### Mapas y análisis geoespacial
https://bastianolea.rbind.io/blog/mapas_sf/

https://bastianolea.rbind.io/blog/tutorial_mapa_chile/

https://bastianolea.rbind.io/blog/tutorial_mapa_urbano/

https://bastianolea.rbind.io/tags/mapas/


### Reportes
https://bastianolea.rbind.io/blog/quarto_reportes/

https://bastianolea.rbind.io/blog/quarto_params/

https://bastianolea.rbind.io/blog/tutorial_quarto_github_pages/

https://bastianolea.rbind.io/tags/quarto/


### Aplicaciones
https://bastianolea.rbind.io/blog/r_introduccion/tutorial_shiny_1/

https://bastianolea.rbind.io/tags/shiny/


### Web scraping
https://bastianolea.rbind.io/blog/r_introduccion/web_scraping/

## Publica, comparte y expándete

https://bastianolea.rbind.io/blog/r_introduccion/tutorial_shinyapps/

https://bastianolea.rbind.io/blog/r_introduccion/tutorial_github/


----

## Avanzado

#### Shiny avanzado

https://bastianolea.rbind.io/tags/shiny/


----

## Sobre

```{r}
div(style = "text-align: center;",
    img(src = "awawa.png", alt = "awawa", 
        style = "max-width: 50%; border-radius: 50%;")
)
```
